// lib/onboarding/demoTemplates.ts
export type DemoTemplate = {
  title: string;
  description: string;
  body_markdown: string;
  pinned?: boolean;
};

export const DEMO_TEMPLATES: DemoTemplate[] = [
  {
    title: "要件定義を最速で固める（Webアプリ）",
    description: "Goal/Context/Constraints を整理して、開発にそのまま渡せる要件定義プロンプト。",
    pinned: true,
    body_markdown: [
      "# 要件定義プロンプト（Webアプリ）",
      "",
      "## Goal",
      "- 作りたいプロダクトの目的・成功条件を明確化する",
      "",
      "## Context",
      "- ターゲットユーザー / 想定ユースケース / 現状課題",
      "",
      "## Constraints",
      "- 期限 / 予算 / 使用技術 / 運用 / セキュリティ / 法的制約",
      "",
      "## Output format",
      "1) プロダクト概要（1段落）",
      "2) ユーザーストーリー（箇条書き）",
      "3) 画面一覧と各画面の目的",
      "4) データモデル案（テーブルと主要カラム）",
      "5) API/ワークフロー案（箇条書き）",
      "6) 未確定点（質問リスト）",
      "",
      "## Instructions",
      "- 不明点は先に質問し、仮定を明示して進める",
      "- 具体例（サンプル文言）も入れる",
    ].join("\n"),
  },
  {
    title: "UI改善レビュー（Next.js / Tailwind）",
    description: "画面の改善点を、優先度付きで具体的に提案してもらう。",
    pinned: true,
    body_markdown: [
      "# UI改善レビュー",
      "",
      "## Goal",
      "- 現在の画面を「スタイリッシュ＆信頼感」に寄せて改善する",
      "",
      "## Context",
      "- Next.js（App Router）",
      "- Tailwind CSS",
      "- B2B寄りの信頼感を重視",
      "",
      "## What I will provide",
      "- 画面スクショ or HTML/TSXコード or URL",
      "",
      "## Output format",
      "- 1) 問題点（UX / 視認性 / 情報設計）",
      "- 2) 改善案（すぐ直せる順）",
      "- 3) 具体的なTailwind修正例",
      "",
      "## Constraints",
      "- 変更は最小・破壊的変更は避ける",
      "- モバイル最優先（1カラム前提）",
    ].join("\n"),
  },
  {
    title: "Dify Workflow 入出力設計（安定化）",
    description: "Difyの揺れる出力を吸収しつつ、安定したAPI設計に落とす。",
    pinned: false,
    body_markdown: [
      "# Dify Workflow 入出力設計（安定化）",
      "",
      "## Goal",
      "- どんな出力揺れでも { generated_prompt, explanation } に正規化する",
      "",
      "## Context",
      "- Dify workflow run（blocking）を使用",
      "- 出力が text/answer/outputs/result 等で揺れる可能性がある",
      "",
      "## Output format",
      "- APIの入出力仕様（JSON）",
      "- 正規化ロジックの優先順位",
      "- 失敗時の取り扱い（ログ/ユーザー表示）",
      "",
      "## Instructions",
      "- 例外ケース（空文字、JSON文字列、入れ子）も考慮",
      "- 実装は Next.js Route Handler を想定",
    ].join("\n"),
  },
];
